import{a as P,S as $,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&f(m)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const B="55066588-ed2d39315576c70ee50c91166",E="https://pixabay.com/api/";async function g(o,e=1){const r={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await P.get(E,{params:r})).data}const p=document.querySelector(".gallery"),d=document.querySelector(".loader"),M=new $(".gallery a",{captionsData:"alt",captionPosition:"bottom"});function L(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <p> likes: ${r.likes}</p>
      <p> views: ${r.views}</p>
      <p> comments: ${r.comments}</p>
      <p> downloads: ${r.downloads}</p>
    </li>
  `).join("");p.innerHTML=e,M.refresh()}function H(){p.innerHTML=""}function w(){d&&d.classList.remove("is-hidden")}function v(){d&&d.classList.add("is-hidden")}const u=document.querySelector(".load-more");function S(){u&&u.classList.remove("is-hidden")}function a(){u&&u.classList.add("is-hidden")}const b=document.querySelector(".form"),h=b.querySelector('input[name="search-text"]'),O=document.querySelector(".gallery"),y=document.querySelector(".load-more");let c="",i=1;const q=15;let l=0;b.addEventListener("submit",async o=>{if(o.preventDefault(),c=h.value.trim(),i=1,c===""){n.error({message:"Please enter a search query."});return}H(),a(),w();try{const e=await g(c,i);if(l=e.totalHits,!e.hits.length){n.error({message:"Sorry, no images found. Try a different search query."});return}L(e.hits),n.success({message:`Hooray! We found ${l} images.`}),i*q<l?S():(a(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){n.error({message:"Something went wrong. Please try again."}),console.error(e)}finally{v(),h.value=""}});y&&y.addEventListener("click",async()=>{i+=1,a(),w();try{const o=await g(c,i);if(!o.hits.length){a(),n.info({message:"We're sorry, but you've reached the end of search results."});return}const e=O.firstElementChild,r=e?e.getBoundingClientRect().height:0;L(o.hits),r&&window.scrollBy({top:r*2,behavior:"smooth"}),i*q<l?S():(a(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){n.error({message:"Something went wrong. Please try again."}),console.error(o),a()}finally{v()}});
//# sourceMappingURL=index.js.map
