import{a as S,S as b,i as a}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="55066588-ed2d39315576c70ee50c91166",$="https://pixabay.com/api/";function m(o,e=1){const r=`${$}?key=${q}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=12&page=${e}`;return S.get(r).then(c=>c.data)}const y=document.querySelector(".gallery"),u=document.querySelector(".loader"),P=new b(".gallery a",{captionsData:"alt",captionPosition:"bottom"});function g(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <p> likes: ${r.likes}</p>
      <p> views: ${r.views}</p>
      <p> comments: ${r.comments}</p>
      <p> downloads: ${r.downloads}</p>
    </li>
  `).join("");y.innerHTML=e,P.refresh()}function E(){y.innerHTML=""}function p(){u&&u.classList.remove("is-hidden")}function L(){u&&u.classList.add("is-hidden")}document.querySelector(".load-more");const w=document.querySelector(".form"),h=w.querySelector('input[name="search-text"]'),n=document.querySelector(".load-more");document.querySelector(".gallery");let l="",i=1;const v=15;let d=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),l=h.value.trim(),i=1,l===""){a.error({message:"Please enter a search query."});return}E(),n.classList.add("is-hidden"),p();try{const e=await m(l,i);if(d=e.totalHits,!e.hits.length){a.error({message:"Sorry, no images found. Try a different search query."});return}g(e.hits),a.success({message:`Hooray! We found ${d} images.`}),i*v<d?n.classList.remove("is-hidden"):(n.classList.add("is-hidden"),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){a.error({message:"Something went wrong. Please try again."}),console.error(e)}finally{L(),h.value=""}});n.addEventListener("click",async()=>{i+=1,p();try{const o=await m(l,i);if(!o.hits.length){n.classList.add("is-hidden"),a.info({message:"We're sorry, but you've reached the end of search results."});return}const e=document.querySelector(".gallery a"),r=e?e.getBoundingClientRect().height:0;g(o.hits),r&&window.scrollBy({top:r*2,behavior:"smooth"}),i*v>=d&&(n.classList.add("is-hidden"),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){a.error({message:"Something went wrong. Please try again."}),console.error(o)}finally{L()}});
//# sourceMappingURL=index.js.map
